version: '2.1'

services:
  adfs-proxy:
    image: adfs-proxy
    environment: 
      MONGODB_URL: mongodb://localhost:27017
      MONGODB_NAME: kanban
      SESSION_SECRET: 123
    build: .
    ports:
      - 3000:3000